### ISSUE TITLE
Support for k-callstring & Evaluate different approaches to context-sensitivity

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#1038]
As a result around some discussion what it means for a tool to be a framework, I think it might be interesting to add the ability to use k-callstrings in Goblint. The implementation of it should be trivial, but it might be worth comparing:

- Does it help Goblint to be more precise when enabled together with our usual contexts on sv-comp?
- How does it compare to our normal approach to context-sensitive analysis, i.e., partial tabulation, w.r.t. precision and performance?

This might also be the basis for a Bachelor's thesis to do some larger scale measurements on all our different options for contexts.

**Comment by sim642** [comment]
We have some old stack trace analyses here, which essentially can just use call strings as context:
https://github.com/goblint/analyzer/blob/17348bec5283822b54b6dd4503a8bb7b617a15ed/src/analyses/stackTrace.ml and https://github.com/goblint/analyzer/blob/17348bec5283822b54b6dd4503a8bb7b617a15ed/src/cdomains/stackDomain.ml.

Instead of a hard-coded limit it would also be possible to have prefix-set callstrings like we do for thread IDs.
