### ISSUE TITLE
`PathSensitive2`: Avoid quadratic complexity for `map` by grouping/hashing

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#1039]
### Issue:
The `map` operation in the `PathSensitive2` functor performs a quadratic number of `should_join` calls in the number of paths. In a modified version of regression test `08/02` with 9 malloced variables, where the `malloc_null` analysis is activated, there a considerable amount of time is spent in `Constraints.PathSensitive2.map` and in particlar in `BatSet.add` operations:
![Bildschirmfoto vom 2023-05-05 15-42-30](https://user-images.githubusercontent.com/5951582/236476841-0f87859a-7a8a-486e-9794-24bc00ff7bfd.png)

In case of 9 malloced variables, there are 2^9 paths, leading to a number of comparisons in the order of magnitude of (2^9)^2. 

### Solution:
The idea is to avoid the comparison of all paths to build the set of paths. To that goal, one could demand that each analysis provides an additional hash function `hash'`, such that `should_join d1 d2` implies `hash' d1 = hash' d2`. Then, one can use the `hash'` to build buckets in which a mutual `should_join` comparison has to be performed.

As this approach would require to maintain a separate `hash'` function for each analysis, a modified solution (proposed by @michael-schwarz) may be preferable:
The `should_join` function would be modified to return the following type ` True | Eq | ShouldJoin of 'a -> 'a -> bool`. 
The `Eq` would mean that the should join is defined via the equality of the analysis states (`D.equal`), `True` would mean that the every pair of states should be joined, and the `ShouldJoin of 'a -> 'a -> bool` could be any custom should join function.

Then, building the set of paths in the `PathSensitive2.map` could rely on this information:
For analysis for which the `shouldjoin` returned `Eq`, the regular hash function of the analysis domain can be used to obtain  buckets, so that joins of paths only occur within buckets. For `ShouldJoin`, one may use a constant hash function.

As there are multiple analyses, the buckets should be split by the combination (e.g. the product) of those hashes.

**Comment by michael-schwarz** [comment]
> At some point I remarked that all of our should_joins are actually just projective

They currently may be, but there is nothing preventing the addition of new ones that aren't, in which case it would go wrong.

**Comment by sim642** [comment]
It wouldn't _go wrong_, it just wouldn't be definable. `DisjointDomain.CombinedSet` already allows for mixing projected and pairwise buckets. If the need arises, generalizing from `ProjectiveSet` is easily possible.

**Comment by sim642** [comment]
I think that requires some more benchmarking though because maybe in that case the outer hashconsing is unnecessary. There's also some non-obvious overhead to hashconsing.
For example, even with both optimizations, there's a considerable amount of time spent on `hash` calculations. That is because the mere creation of a hashconsed object requires calling its `hash` and that traverses over its entire contents. But it could even be that no hashconsing is faster. The reason being, `equal` and `compare` are short-circuiting and terminate on the first difference, but `hash` cannot short-circuit since it's evaluated individually. Thus it could sometimes be cheaper to directly `equal` rather than `hash`ing both elements for hashconsing and then comparing their integer tags.
