### ISSUE TITLE
ArithmeticOnIntegerBot exceptions in SV-COMP SoftwareSystems

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#115]
In my own run of Goblint on SV-COMP SoftwareSystems category, Goblint crashed with `ArithmeticOnIntegerBot` exception on the following benchmarks:

- [ ] ldv-linux-3.0/usb_urb-drivers-vhost-vhost_net.ko.cil.out.i (line 7168, `bottom op [-2147483648,2147483647]`)
- [ ] ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-orinoco-orinoco_usb.cil.i (line 7732, `[0,0] op bottom`)
- [ ] ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--usb--gadget--udc--net2272.ko.cil.i (line 6546, `[0,0] op bottom`)

After the `hidden` parse error fix (https://github.com/goblint/cil/issues/18, https://github.com/goblint/cil/commit/26847e87655fa7a5c8d9e14d9d9cee81eee6b290) another one appeared:
- [ ] ldv-consumption/32_7a_cilled_linux-3.8-rc1-drivers--vfio--pci--vfio-pci.ko-main.cil.out.i (line 4343, `Error int op 0`)

**Comment by michael-schwarz** [comment]
When this happens it usually is related to cases where our int domains are unsound. Julian is working on a fix for these issues in a separate branch.
See also #98. While that PR is closed, the issues described there are still up-to-date.

**Comment by jerhard** [comment]
@sim642 How are you running these benchmarks? Is there a simple way to reproduce these results?

**Comment by jerhard** [comment]
I could reproduce the failure of the first test case now (without relying on benchexec).

**Comment by jerhard** [comment]
Minimal test case for the first issue:
https://github.com/goblint/analyzer/blob/ae6149b38413f373634eec6bfd897789cb0c7bdf/tests/regression/29-svcomp/12_interval_bot.c#L5-L10
The bottom value that is then computed seems to arise in the following code in `Base.invariant` for the value in the interval domain:
https://github.com/goblint/analyzer/blob/a09bb382d339f73e59997605839468db4b959433/src/analyses/base.ml#L1490-L1502

The problem arises because the "Top" of the interval domain is represented by `[-2^31, 2^31-1]`. Intersecting it with an interval `starting` from >`2^31-1` will produce bottom.

**Comment by michael-schwarz** [comment]
> The problem arises because the "Top" of the interval domain is represented by `[-2^31, 2^31-1]`. Intersecting it with an interval `starting` from `>2^31-1` will produce bottom.

Interesting that this happens despite the calls to `norm` in `starting` and `ending`.

**Comment by jerhard** [comment]
As a quick fix, I would return `top` in `starting` / `ending`, if `n` is out of range `[-2^31, 2^31-1]`.
https://github.com/goblint/analyzer/blob/533c0c36d71583d9b0546427cdc879762886d96f/src/cdomains/intDomain.ml#L228-L238

**Comment by jerhard** [comment]
For the second failure, I extracted a minimal test case here:
https://github.com/goblint/analyzer/blob/b211689847f8ea781be100f75ebb02f20610028c/tests/regression/29-svcomp/13_comparision_bot.c#L4-L8
The problem here was that we calculated with values outside of the range of `unsigned int`. Adding a cast to the right type in `evalbinop` (in the example -256 is casted back to `unsigned int`) fixes this.
