### ISSUE TITLE
Make fast_global_inits work for Partitioned Arrays

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#122]
Currently, we need to turn off `fast_global_inits` for running with partitioned arrays.
This mean executing `n*m` assigns to `0` for a zero-initialized global array `a[n][m]` which is expensive.
We can avoid this by adding a special function to initialize a complete array to `0` to the array domain.

**Comment by sim642** [comment]
I'm not familiar with the array domains but instead of having `fast_global_inits` generate the assign edge `a[0] = 0` for a zero-initialized array, couldn't we just generate the assign edge `a[unknown_exp] = 0` instead? Since our global initializers are done with edges as intermediates, this might avoid having to add new special mechanisms for handling this.

**Comment by michael-schwarz** [comment]
> Couldn't we just generate the assign edge `a[unknown_exp] = 0`

No, we wouldn't gain anything by this. At best we might know that `a` is `0` at `unknown_exp` and nothing else about the rest of the array.
In fact, it is even worse, as `unknown_exp` can not be used to partition an array, so we would weakly update `T \lub [0,0] = T` for the entire array.

**Comment by vogler** [comment]
Maybe use a special `zero_init` expression that `assign` can react to?

**Comment by michael-schwarz** [comment]
Merged #133 for now, if we ever want to properly support initializers (i.e. not just zero), the way to go would probably be similar to #129.

**Comment by michael-schwarz** [comment]
I tested it on the sv-comp examples from the system category, it does not really make a difference there with a 1 minute timeout.
I will start another run, with a 5 minute timeout, maybe we see more interesting cases there.
