### ISSUE TITLE
Better handling of calls to `malloc` wrapped inside functions such as `ldv_malloc`

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#123]
This is a follow-up to #119:

A lot of tests in `sv-comp` wrap calls to `malloc` into calls to the helper function `ldv_malloc`. We only have one abstract heap object for all memory allocated via `ldv_malloc` (as the `malloc` for these calls is always in the same place), which might be a big source of imprecision.

The easiest solution would be to treat `ldv_malloc` specially just like we do `malloc`, but according to @sim642 there are different versions of `ldv_malloc` with some of them also simulating failing `malloc` calls while normally we can assume them to succeed in `sv-comp`.

Another approach would be to have some limited form of context-sensibility specifically for memory allocated inside functions such as `ldv_malloc`.

**Comment by sim642** [comment]
The benchmark that I minimized in #119 is also one that explicitly encodes the possibility of failing into `ldv_malloc`: https://github.com/sosy-lab/sv-benchmarks/blob/f32eef1e13ae15f9ff593374b66ac82a4eed8f49/c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--usb--host--isp1362-hcd.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i#L3754-L3763. It makes no difference to that crash but it's where I noticed such a thing.

I haven't investigated how common this is, but considering how SV-COMP by default assumes `malloc` never failing:

> malloc(), free(): We assume that the functions malloc and alloca always return a valid pointer, i.e., the memory allocation never fails, and function free always deallocates the memory and makes the pointer invalid for further dereferences. 

It seems very likely that benchmarks use wrapper versions which either use `malloc` directly or add failure to it.

**Comment by michael-schwarz** [comment]
> `__kmalloc`, `kmalloc` and `kzalloc`

I think we handle these already in Goblint.

**Comment by sim642** [comment]
Oh yeah, I forgot about that. That could be problematic though because as special functions we'd then be assuming they don't fail while if implemented through a possibly failing `ldv_malloc` or whatever, they actually could. It would make us unsound.

**Comment by sim642** [comment]
Unsurprisingly, a new unsoundness case in #120 is exactly because of special handling of `kzalloc` in which the benchmark actually has an error call that we therefore miss.

- [ ] ldv-linux-3.16-rc1/43_2a_bitvector_linux-3.16-rc1.tar.xz-43_2a-drivers--media--platform--timblogiw.ko-entry_point.cil.out.i

**Comment by michael-schwarz** [comment]
> Unsurprisingly, a new unsoundness case in #120 is exactly because of special handling of kzalloc in which the benchmark actually has an error call that we therefore miss.

So I guess for `sv-comp` we should stop treating `kzalloc`, and other such things as special functions that map to `Malloc` and instead analyze them (and maybe have this treating them as `Malloc` as a fallback in case we don't encounter a body and only a prototype).

**Comment by sim642** [comment]
The unsoundness aspect shouldn't be difficult to fix because if a function has a definition and is also special, we analyze it normally:
https://github.com/goblint/analyzer/blob/5999bcfa4abdd44961ae0351d2a062b023e92911/src/framework/constraints.ml#L628-L631

The overrides to that are defined here, where `kzalloc` is also listed:
https://github.com/goblint/analyzer/blob/5999bcfa4abdd44961ae0351d2a062b023e92911/src/analyses/libraryFunctions.ml#L454-L456

Removing `kzalloc` from that list makes the result `unknown`, fixing the unsoundness. Based on the above discussion, it might make sense to similarly remove `kmalloc` from that list as well. But before we jump the gun, **does anyone know why we have such exceptions at all?** My initial guess would be the same reason from above: somewhere `kzalloc` had a definition via some other alloc function but a better (outer scope) location was desired for precision, so this was forcefully special cased to provide that.

**Comment by sim642** [comment]
According to git blame, these exceptions were originally added by @vesalvojdani: https://github.com/goblint/analyzer/commit/cefd7c7340c54b961443d5f030e02a4bec68e17c#diff-f11dd379df0d8dcedf47eec4569e585bdf20a8671f9194a6cdfd69e65ce0c4e5R405-R406.

**Comment by vesalvojdani** [comment]
Yes, almost certainly to avoid all allocs to collapsing to the same location. Ideally, stack traces should be used to distinguish these more robustly, but probably this was an easier fix.

**Comment by michael-schwarz** [comment]
We decided to have a separate analysis that keeps track of the location of the call of some special functions such as `ldv_malloc`, `kzalloc` etc. In the special edge for `malloc` we will then `ask` this analysis for what `varinfo` this is represented by, which it either retrieves from the hashmap or creates and adds to the hashmap.

This way, this is separated from all the things the base analysis does and becomes an easily changeable thing.

**Comment by sim642** [comment]
That's something I thought about as well. The downside is having to put together a list of such functions that matches the ones occurring in sv-benchmarks.

Something stack trace based would avoid that manual work. We have some stack trace analysis implementations but they also affect function contexts, not just the allocations. Anyway, if the query mechanism for heap variables in in place then this can be experimented with more.

I will remove `kzalloc` and `kmalloc` from the exception list for now.

**Comment by michael-schwarz** [comment]
>  but they also affect function contexts

The thing we propose also means putting this information into the context as well, otherwise you'd once again end up with a situation where calls to sth like `ldv_malloc` in different lines are represented by the same heap variable, as we'd just join locations then (yielding some sort of top location).

> Something stack trace based would avoid that manual work.

I guess if you want to do this completely automatically without specifying such a list of `malloc_wrappers`, you'd have to keep around call stacks for all invocations, which would be some sort of weird hybrid between our context-based thing and the callstring approach.

> put together a list of such functions that matches the ones occurring in sv-benchmarks

Should we ask on the mailing list if having such a list would be rule-compliant for SV-Comp?

**Comment by sim642** [comment]
> The thing we propose also means putting this information into the context as well, otherwise you'd once again end up with a situation where calls to sth like `ldv_malloc` in different lines are represented by the same heap variable, as we'd just join locations then (yielding some sort of top location).

Right, but if you only remember the interesting alloc functions in the context, not arbitrary functions, then I guess it shouldn't cause any difference outside of any of these interesting functions. We can discuss the exact details and impact once you have this working in some form.

> Should we ask on the mailing list if having such a list would be rule-compliant for SV-Comp?

I don't think that's an issue because that'd just be part of an SV-COMP-optimized configuration. Then it's just on us to keep that list up to date and sufficiently complete, which is a disadvantage in itself compared to a less manual approach.

**Comment by ivanazuzic** [comment]
We still need to figure out what functions to choose as malloc wrappers for SV-COMP.

**Comment by michael-schwarz** [comment]
> We still need to figure out what functions to choose as malloc wrappers for SV-COMP.

I can do this based on this syntactic search feature my student implemented, we should be able to extract a list of how often a method with some name acts as a malloc wrapper and then decide based on that,

**Comment by sim642** [comment]
That would be great, a true test for the student's work!

By the way, CPAchecker's SV-COMP configuration (although for memory safety) also lists some here:
https://github.com/sosy-lab/cpachecker/blob/a51a5d9ba8b2e5e2abaaca9b8f1b4f928ff54bb5/config/svcomp21--memorysafety.properties#L50-L60.
We could probably add those to our svcomp21 list as well.

**Comment by sim642** [comment]
I added the ones we were missing from CPAchecker's list (https://github.com/goblint/analyzer/commit/19280b49fb436b671064ebb7353dafc862650cf3) and benchmarked SoftwareSystems for comparison. I saw a few dozen performance regressions, so I thought the list got slightly too big to be checked on each function call and quickly implemented the `Hashtbl` version on top of it (https://github.com/goblint/analyzer/commit/582423fc9b2e8cfa57a3a2686053e93ce54d74bc) and benchmarked that also.

Doing a 3-way comparison there were no notable differences (even between the first two!) and I realized I must've compared it with wrong previous results. So there weren't any performance regressions nor did it improve anything. But since I already implemented the `Hashtbl` version and it doesn't regress, I'll just merge that one even though it isn't currently necessary.
