### ISSUE TITLE
Define a `make` target for running relational tests

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#1359]
Currently, one has to run a ~5 sets separately after making changes to something related to apron. This is inconvenient.

**Comment by sim642** [comment]
I've wanted to do something even broader for a while: set up dune rules such that `dune runtest` would run all the tests we have. `make test` could just be an alias for it.
Dune does dependency tracking, so it does the minimum amount of work required to rerun everything. Our `make` doesn't because it just delegates to a shell script which is oblivious and would always redo everything.
Also `dune runtest` guarantees that you don't forget to rebuild Goblint before running the tests.
