### ISSUE TITLE
Goblint not reaching fixpoint on some SV-COMP tests

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#139]
For some of the SV-comp examples in `ReachSafety-ProductLines` Goblint fails to reach a fixpoint:

```
product-lines/minepump_spec2_product32.cil.yml 
product-lines/minepump_spec2_product33.cil.yml 
product-lines/minepump_spec2_product34.cil.yml 
product-lines/minepump_spec2_product35.cil.yml 
product-lines/minepump_spec2_product36.cil.yml 
product-lines/minepump_spec2_product37.cil.yml 
product-lines/minepump_spec2_product38.cil.yml 
product-lines/minepump_spec2_product39.cil.yml 
product-lines/minepump_spec2_product40.cil.yml 
product-lines/minepump_spec2_product41.cil.yml 
product-lines/minepump_spec2_product42.cil.yml 
product-lines/minepump_spec2_product43.cil.yml 
product-lines/minepump_spec2_product44.cil.yml 
product-lines/minepump_spec2_product45.cil.yml 
product-lines/minepump_spec2_product46.cil.yml 
product-lines/minepump_spec2_product47.cil.yml 
product-lines/minepump_spec2_product48.cil.yml 
product-lines/minepump_spec2_product49.cil.yml 
product-lines/minepump_spec2_product50.cil.yml 
product-lines/minepump_spec2_product51.cil.yml 
product-lines/minepump_spec2_product52.cil.yml 
product-lines/minepump_spec2_product53.cil.yml 
product-lines/minepump_spec2_product54.cil.yml 
product-lines/minepump_spec2_product55.cil.yml 
product-lines/minepump_spec2_product57.cil.yml 
product-lines/minepump_spec2_product56.cil.yml 
product-lines/minepump_spec2_product58.cil.yml 
product-lines/minepump_spec2_product59.cil.yml 
product-lines/minepump_spec2_product60.cil.yml 
product-lines/minepump_spec2_product61.cil.yml 
product-lines/minepump_spec2_product62.cil.yml 
product-lines/minepump_spec2_product63.cil.yml 
product-lines/minepump_spec2_product64.cil.yml 
product-lines/minepump_spec2_productSimulator.cil.yml
list-simple/dll2c_update_all.yml          
list-simple/dll2c_update_all_reverse.yml  
list-simple/dll2n_update_all.yml 
list-simple/sll2c_update_all.yml
list-simple/sll2c_update_all_reverse.yml    
list-simple/sll2n_update_all.yml 
list-simple/sll2n_update_all_reverse.yml
```

I tried running most of them without the `sv-comp` analysis and in this case it works. So this seems to be related to witness generation somehow.

**Comment by sim642** [comment]
This seems to be caused by narrowing in `PathSensitive3` and its `HoareMap`. Even though at one point I did implement `HoareSet`-like operators for it (https://github.com/goblint/analyzer/commit/94af42655d739861445501decf15be0e97e77543), their behavior on values/ranges still might not be right.

`product-lines/minepump_spec2_product32.cil.yml` seemed to work just fine for me so I investigated `product-lines/minepump_spec2_product33.cil.yml` instead. When narrowing was applied, the keys were correctly updated but the corresponding ranges got screwed up and stayed at their old values, causing things to go out of sync.

I pushed some kind of fix to the [`hoare/issue-139`](https://github.com/goblint/analyzer/tree/hoare/issue-139) branch that at least solves the problem for these benchmarks. I didn't test anything else though so it might now cause other issues. I'll have to test these changes more and better understand what is happening.
