### ISSUE TITLE
Port Enums Domain to BigInt 

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#160]
Use `BigInt` in the implementation of the  `Enums` domain and take the `ikind` of `int`s into account when performing abstract operations.

**Comment by michael-schwarz** [comment]
While we are on this, we should also once again define what exactly we want the enum domain to do. I'm not sure if there is consent on this right now.

**Comment by jerhard** [comment]
>define what exactly we want the enum domain to do

What are the open points? I guess we should discuss in particular the following things:
- should arithmetic operations try to keep information or always go to top
- when do we want to enforce the size bound for sets/exclusion sets:
    - in arithmetic operations (in case they don't go to top, see point above)
    -  in `join`s
    - in `meet`s
    - in `of_interval` and in `of_excl_list`?
- How should `DefExc` and `Enums` relate? In particular, if we keep precise information for arithmetic operations in `Enums`, is there still a need for `DefExc`? (In #52 there were plans to remove `DefExc` a.k.a. `Trier`)

**Comment by michael-schwarz** [comment]
> should arithmetic operations try to keep information or always go to top

In order to not make them some sort of `DefExc` except that it is a `IncExc`, I would suggest making them go to top.

> when do we want to enforce the size bound for sets/exclusion sets

This is a good point: In DefExc we have no fixed bound on the number of excluded elements. Can we maybe get away with the same logic here? I guess the only real blow-up that happens is because of arithmetic operations?

I guess we should discuss this at the next GobCon maybe?

**Additional, tangentially related, point:** Right now, we don't make use of the fact that things that are an enum in the C program actually have type `TEnum` which has an `enuminfo` value.  https://people.eecs.berkeley.edu/~necula/cil/api/Cil.html#TYPEenuminfo.

I was initially hoping one could restrict the possible values of a variable of type `enum` to the ones appearing in the enumeration. Unfortunately, the standard allows any integer value that fits into the `integer type` chosen by the compiler to represent the enum, so we can't really gain anything there. However, it might still be interesting to warn when doing things that lead to values outside the members of an enumeration, as this could point to a bug.

**Comment by sim642** [comment]
My vague memory from a GobCon discussion before SV-COMP is that `Enums` is supposed to handle possible values for enums (duh!) on which arithmetic operations don't really make sense. In that view, it would be fine for arithmetic operations to go to top.

The question of boundedness is separate for inclusion and exclusion sets. Seems to me that in the current implementation inclusion sets are bounded with `ana.int.enums_max` while exclusion sets are unbounded (like in `DefExc`). I also wonder if we could be unbounded on inclusion sets here as long as arithmetic goes to top. Then the inclusion set cannot keep growing infinitely but would be limited to just the finite number of literals in the source code. The size of such set shouldn't really be a problem if there's no attempt to do quadratic pairwise arithmetic operations.

Another point I'd like to bring up is that `DefExc` uses an actual set while `Enums` uses a list of elements (and keeps them sorted it seems). Might be reasonable to have `Enums` also use sets instead of lists.

But if we're already suggesting so many changes to `Enums`, it seems like it would mostly have to be reimplemented from scratch.

**Comment by jerhard** [comment]
Helmut thinks we should only perform arithmetic logic for singleton sets, and additionally "trivial" cases like multiplication with 1, or 0.

**Comment by vogler** [comment]
> My vague memory from a GobCon discussion before SV-COMP is that `Enums` is supposed to handle possible values for enums (duh!) on which arithmetic operations don't really make sense. In that view, it would be fine for arithmetic operations to go to top.

The idea was to have this adjustable via `ana.int.enums_max` where the default goes to top on any operation in a cycle to ensure termination.
(Of course if you are not in a cycle but just have `n > enums_max` sequential paths joined, you will also go to top on arith. op., but our analyses/domains don't know about cycles the solver may determine.)

> The question of boundedness is separate for inclusion and exclusion sets. Seems to me that in the current implementation inclusion sets are bounded with `ana.int.enums_max` while exclusion sets are unbounded (like in `DefExc`). I also wonder if we could be unbounded on inclusion sets here as long as arithmetic goes to top. Then the inclusion set cannot keep growing infinitely but would be limited to just the finite number of literals in the source code. The size of such set shouldn't really be a problem if there's no attempt to do quadratic pairwise arithmetic operations.

Also see https://github.com/goblint/analyzer/pull/175#discussion_r612602808
As long as there are no arithmetic operations, the inclusion is unbounded as well since join/widen don't jump.
If there are cycles with arithmetic operations, you need some bound for the computed values though. This can be set via `ana.int.enums_max`.

> Another point I'd like to bring up is that `DefExc` uses an actual set while `Enums` uses a list of elements (and keeps them sorted it seems). Might be reasonable to have `Enums` also use sets instead of lists.

See https://github.com/goblint/analyzer/pull/175#discussion_r612592829
