### ISSUE TITLE
Maradns: Unexpected results with default analyses

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#177]
@vogler identified some issues where Goblint behaves unexpectedly:

The analysis of the `maradns` benchmark https://github.com/goblint/bench/blob/master/single-thread/maradns-1.4.06_comb.c apparently takes `~2 min` with only the base analysis (and `ana.int.interval`) activated (regardless of `exp.full-context` being active or not).

However, with the default analyses `['expRelation','base','threadid','threadflag','escape','mutex', 'mallocWrapper']` enabled, it only behaves ok when `exp.full-context` is on, while it does not terminate when `exp.full-context` is off.

**Comment by michael-schwarz** [comment]
I tried to reproduce it locally (based on Ralf's benchmark table Helmut sent me), and don't see any difference between `exp.full-context` on or off, Goblint does not seem to terminate in a reasonable amount of time when the default analyses are active regardless of `exp.full-context`:

`./goblint -v ../bench/single-thread/maradns-1.4.06_comb.c --enable exp.solver.td3.space --enable exp.earlyglobs --enable ana.int.interval --disable ana.int.enums --disable ana.int.def_exc --enable exp.full-context --disable exp.widen-context --disable exp.solver.td3.space_restore`

vs.

`./goblint -v ../bench/single-thread/maradns-1.4.06_comb.c --enable exp.solver.td3.space --enable exp.earlyglobs --enable ana.int.interval --disable ana.int.enums --disable ana.int.def_exc --disable exp.full-context --disable exp.widen-context --disable exp.solver.td3.space_restore`

behave identically on 20f3a7d6285a35c7c7d5c2f6206e280a73b83c25.

**Comment by michael-schwarz** [comment]
For some reason, enabling `threadflag` makes the analysis much more expensive: It went from terminating in 60s to taking `>8min` for sure.

**Comment by michael-schwarz** [comment]
The problem seems to be somehow related to how `earlyglobs` is set to `false` during global initialisation. If I remove that, it terminates regardless of `threadflag` being active or not.

I think the interesting piece of code is this one in base.ml: If the ThreadFlag analysis is not active, ThreadFlag.is_multi will always return true, so we always go into the second branch
https://github.com/goblint/analyzer/blob/20f3a7d6285a35c7c7d5c2f6206e280a73b83c25/src/analyses/base.ml#L1835

If however, I patch `ThreadFlag.is_multi` to return false when we are in the initialization phase (as it would have been before we split these analyses), having just `['base','mallocWrapper']` on also leads to non-termination.
 Maybe that helps @vogler?

**Comment by sim642** [comment]
> The problem seems to be somehow related to how `earlyglobs` is set to `false` during global initialisation.

This confused me at one point as well. In `traces` branch I "fixed" it, but that required simulating `sideg` in some global initialization `ctx`s: https://github.com/goblint/analyzer/commit/ec37c28c6604a032a1b6f3069c5c49e6d79d057c#diff-6463fdbeebd7b3b5d34874cea9c6c84b32977d3596ffcf601463c5a0f4be2b6dR270. I guess the lack of that was the reason for keeping `earlyglobs` off during global initialization. Another thing leading to #178.


> If however, I patch `ThreadFlag.is_multi` to return `false` when we are in the initialization phase (as it would have been before we split these analyses)

And yet another victim of #178. If queries weren't all top during global initialization this would be avoided.

**Comment by vogler** [comment]
Thanks for checking. I named a folder the wrong way - the difference is really just in the activated analyses, not full-context.

What should we do? To make sure I understand:
1. Setting `earlyglobs` to `false` is a hack needed unless #178 is done?
2. `CPA.filter_class 2 cpa` (1. branch) will keep all globals in the entry state and makes it take forever. Why? Too many globals and thereby too many contexts or reevaluations due to changing globals (I guess this)?
3. `CPA.filter (fun k v -> V.is_global k && is_private ctx.ask ctx.local k) cpa` (2. branch) will not keep any globals in the entry state and terminate fast because `is_private` returns `false` because `ThreadFlag.is_multi` returns  `true`?

> If however, I patch `ThreadFlag.is_multi` to return `false` when we are in the initialization phase (as it would have been before we split these analyses), having just `['base','mallocWrapper']` on also leads to non-termination.

How did you change it exactly? Why does it also not terminate? It still takes the 2. branch but now `is_private` gives `true` during initialization and that's enough?

---
Aside: why these cryptic magic numbers? Should we change it to (polymorphic) variants?
https://github.com/goblint/analyzer/blob/0df380bc67e1df90533f64d44d62a905f0ca3687/src/cdomains/basetype.ml#L85-L97

**Comment by sim642** [comment]
> 1. Setting `earlyglobs` to `false` is a hack needed unless #178 is done?

I don't remember what happens on `master` when setting it to `get_bool "exp.earlyglobs"` already at the beginning. Possibly something might `sideg` during global initialization, which crashes.

I did link to a commit I made in `traces` branch to work around it. I suppose it could be carefully cherry-picked to `master` if that works and is useful.


> Aside: why these cryptic magic numbers? Should we change it to (polymorphic) variants?

If I remember correctly, the whole map domain classification thing is just used to slightly improve `CPA.pretty` by grouping the classes. And apparently used here for `filter_class`, but that could easily be done with a normal `filter` too and be more clear.

I wouldn't bother refactoring those magic class numbers to variants. Might be more sensible to just remove them because they're hardly useful since outputs like `--html` don't even expose that. We could still keep it around but just in `CPA` specifically to reduce the map domain interface and do the `varinfo -> string` classification directly (no intermediate numbers).

**Comment by michael-schwarz** [comment]
> How did you change it exactly? Why does it also not terminate? It still takes the 2. branch but now is_private gives true during initialization and that's enough?

I changed `ThreadFlag.is_multi` and added

~~~OCaml
if !GU.global_initialization then false else
~~~

This change makes it consistent with what we had before we made the threadflag a separate thing. So here (assuming I leave this logic for setting `GU.earlyglobs` to `false` during intialization), it takes the first branch during initialization and hence it takes forever.

> I don't remember what happens on master when setting it to get_bool "exp.earlyglobs" already at the beginning.

I think Simmo added some support for this in 4534d3cff2d918e55b0b0a60f5bbbb0909117bd2 where at least for global initializers there are appropriate `gobal` and `sideg`. One would have to check what to do with `enter_with` and `otherstate`.

If I set `GU.earlyglobs` to `get_bool "exp.earlyglobs"` already before the global initialization, at least for our tests nothing crashes, but the initial value of globals is lost:

~~~C
// PARAM: --set exp.earlyglobs true
int g = 10;

int main(void){
  int top;
  if(top) {
      g = 100;
  }

  assert(g==100); //Should be UNKNOWN but we report SUCCESS
  return 0;
}
~~~

Not sure how as initial values seem to be added to the `gh` in `do_global_inits` and then end up in the list `entrystates_global` which is passed to the solver like such `(Slvr.solve entrystates entrystates_global)`.

----

I am also in favor of getting rid of these magic numbers, the solution Simmo proposed sounds reasonable.

**Comment by sim642** [comment]
> I think Simmo added some support for this in [4534d3c](https://github.com/goblint/analyzer/commit/4534d3cff2d918e55b0b0a60f5bbbb0909117bd2) where at least for global initializers there are appropriate `gobal` and `sideg`. One would have to check what to do with `enter_with` and `otherstate`.

Oh you're right. The `traces` branch commit I linked just took that and moved it even earlier so `do_extern_inits` and `enter_with` etc would use it as well.

> Not sure how as initial values seem to be added to the `gh` in `do_global_inits` and then end up in the list `entrystates_global` which is passed to the solver like such `(Slvr.solve entrystates entrystates_global)`.

I have deja vu that I've debugged and understood this at one point in `traces` when fixing `earlyglobs` there. Can't be bothered to do it again, but somehow on that branch works with `old` privatization, so I must've fixed it somehow. My guess is that it has something to do with `main` still starting out in singlethreaded mode (so ignoring global invariant) and the coincidence that the first `sync` in `main` was supposed to actually do the side effects.

This is why I really don't like `earlyglobs` and `allfuns`/`otherfun`: there's so many weird interactions and workarounds piled on top of workarounds that just happen to make it work but impossible to find any reason behind.

**Comment by vogler** [comment]
> This is why I really don't like `earlyglobs` and `allfuns`/`otherfun`: there's so many weird interactions and workarounds piled on top of workarounds that just happen to make it work but impossible to find any reason behind.

Very true. I'm a bit out of the loop - what's the status/plan? Leave `master` as is and eventually merge #183 which cleans up those things as well? Is `traces` in a state to be able to run benchmarks as well or is it WIP?

@michael-schwarz Is that example in our tests?

To recap: if I analyze single-threaded programs and just want `exp.earlyglobs` to keep the globals out of contexts, then I can leave out `threadflag` without any code changes to make it terminate, right?

Maybe we should introduce an option `exp.no-globals-context` so that `exp.earlyglobs` doesn't need to be abused for it.
Could be not much difference in run-time (overwrite vs. join, value changes anyway) but potentially more precise.

Aside: once branches are merged, it's maybe time for sorting out all those `exp.` #28
Also, all the context options should probably be grouped under `ana.context.`.

**Comment by sim642** [comment]
> Very true. I'm a bit out of the loop - what's the status/plan? Leave `master` as is and eventually merge #183 which cleans up those things as well? Is `traces` in a state to be able to run benchmarks as well or is it WIP?

In terms of `earlyglobs` etc, I wouldn't start fixing them on `master` right now because it would probably create conflicts with `traces`, where a dozen different privatization implementations somehow try to not completely break `earlyglobs` etc.

I'd say `traces` is still WIP and even I don't trust the `earlyglobs` etc there.

**Comment by michael-schwarz** [comment]
> @michael-schwarz Is that example in our tests?

No, it is a modified version of `01/32` that highlights the issue better than `01/32` because the assert in `01/32` would succeed in the concrete, whereas here we have `//UNKNOWN!` also in the concrete. I can push that change.

>To recap: if I analyze single-threaded programs and just want exp.earlyglobs to keep the globals out of contexts, then I can leave out threadflag without any code changes to make it terminate, right?

I mean it does terminate, but the analysis is unsound then for the same reason as above :upside_down_face: 

~~~C
// PARAM: --set ana.activated ["'base'","'mallocWrapper'"] --enable exp.earlyglobs
int g = 10;

int main(void){
  int top;
  if(top) {
      g = 100;
  }

  assert(g==100); //Should be UNKNOWN but we report SUCCESS
  return 0;
}
~~~

**Comment by michael-schwarz** [comment]
> @michael-schwarz Is that example in our tests?

It is now with commit 1d4a02de0f41742e78f27d4f278eee98d5a49bac

**Comment by vogler** [comment]
Ok, so to re-recap: `exp.earlyglobs` without `threadflag` is currently unsound and with `threadflag` it does not terminate since it keeps globals in contexts?

**Comment by michael-schwarz** [comment]
Correct.

To make `exp.earlyglob` sound without `threadflag`, one can use the fix to
`ThreadFlag.is_multi` to return `false` during initialization I gave above.
However then we have the termination issue also when `threadflag` is off.

**Comment by vogler** [comment]
I think this can be closed.
`maradns-1.4.06_comb.c` terminates with the config above and `exp.widen-context`.
Apparently it has recursive calls.

After the merge of #183, there's no more special handling for `exp.earlyglobs` in `Base.make_entry`:
https://github.com/goblint/analyzer/blob/6ab27669ec6c3c900c257a039c8f044b44eff43f/src/analyses/base.ml#L1799-L1802
So this relies on globals not being in the local state with `exp.earlyglobs`.
I remember there were some issues that globals were copied into the local state and only `sync`ed out later.
This is no longer the case?
I checked `./regtest.sh 01 32` and the global `g` is never in the local state (as it should).

**Comment by sim642** [comment]
I left the old `new_cpa` line commented out there because I was confused about it. It didn't seem necessary to do the special handling for `earlyglobs` nor the `is_private` filtering to pass our regression tests.

Some of the more involved privatizations do keep written globals in the local state, so I probably had to disable some of the old behavior to get them to work.



> I remember there were some issues that globals were copied into the local state and only `sync`ed out later.
> This is no longer the case?

Global initializers (even with `earlyglobs`) at least used to do this because they couldn't use `sideg` (it was `failwith`). Thus the workaround with `sync`ing them out in the first variable during solving shouldn't be necessary any more, since now globals are simulated during global initializers.

**Comment by vogler** [comment]
Ok, I guess then it should be fine.
I'm just wondering if it could be made safer or if we could create a test for it.
If too many globals are kept in the local state and thereby context, this may lead to analysis taking forever like above.

**Comment by michael-schwarz** [comment]
Stale
