### ISSUE TITLE
Decide what version of OCaml to support & Fix CI accordingly

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#184]
**Current situation**
We currently pretend to build Goblint with Ocaml 4.07.1 and 4.11.1.
However, we do not really compile with `4.07.1`. We specify it in the Github actions

https://github.com/goblint/analyzer/blob/16497fa06d2059f2c3bde130da0bbb89b5a4d6c3/.github/workflows/tests.yml#L17-L19

but then our CI script uses the `pinned` file, installing the pinned version of OCaml.

**General considerations**
Ideally I was hoping to go for a setup like I have for CIL, where we just do everything via opam and dune.

https://github.com/goblint/cil/blob/60e9c5f77a7267591622b94c9be73555cc2881f1/.github/workflows/tests.yml

This is by far the cleanest and would also give us an indication if some package in an updated version is incompatible with Goblint such that we can put a constraint on the maximum version number of some package. Additional advantage is that testing multiple versions of OCaml is a breeze.
Downside is that we would not have reproducible builds as the version of dependencies might change between runs.

**Which OCaml version to support**
We needed 4.07.1 at some point for earlybird, but earlybird now supports later versions. So maybe we can drop support for 4.07.1 now? However, I would still want to keep compatibility with some older versions (e.g. 4.09.1 now), because in my experience it sometimes takes time for e.g. the VSCode plugin (and the language server) to be adapted to a new version of merlin and it is annoying when such things break but you can't go back because Goblint uses new features.

**Comment by sim642** [comment]
> Downside is that we would not have reproducible builds as the version of dependencies might change between runs.

As I suggested in https://github.com/goblint/analyzer/pull/174#discussion_r609915934, we could have a separate CI job that doesn't do multiple versions but does use the lock file. That would at least give reproducible builds with the version of OCaml that we have locked.

---

In terms of the OCaml version, I just remembered that when I tried to use a newer than 4.07 feature in `traces` branch, it didn't work anyway because some ppx dependencies still can only handle 4.07 AST:
https://github.com/goblint/analyzer/blob/e91bdb4b3dfada91c8a729dccc22d5a023b61898/src/analyses/basePriv.mli#L2.
The particular `ppx_import` issue linked in that comment has since been fixed, but I think there was still some other ppx that didn't, so I gave up.

Therefore I'm not really opposed to having 4.07 support as long as the CI nicely checks it.

**Comment by sim642** [comment]
We should probably address this issue before it falls below our radar.

Another incoming aspect with the optional Apron dependency in #196 is that we should CI both no-apron and apron configurations separately. Opam lock files make optional dependencies mandatory, so the CI there currently compiles with Apron and has octApron analysis available.

When developing locally and also installing apron at some point, it's easy to add tests with octApron activated (which pass locally and on the CI), but will fail for anyone else who hasn't installed the optional dependency locally.

**Comment by vogler** [comment]
What's the conclusion on this?

> As I suggested in [#174 (comment)](https://github.com/goblint/analyzer/pull/174#discussion_r609915934), we could have a separate CI job that doesn't do multiple versions but does use the lock file. That would at least give reproducible builds with the version of OCaml that we have locked.

That seems reasonable. But if we e.g. lock 4.12.0, then do we want to run 4.12.0 again without lock or do we skip it?
What old version should we test? Maybe go from `4.07.1` to `4.10.2`?

**Comment by sim642** [comment]
Since the unlocked jobs would also check with possible updates of other packages, it might make sense to repeat that unlocked for 4.12 as well.

The lower bound of 4.07 might still make sense for now since that's the version we've tried to limit ourselves to so far I guess. Not sure if anyone has checked if master still builds with 4.07 though, since the CI doesn't. It would be completely fine to bring the lower bound up as well because there isn't a strict reason to have to support so many OCaml versions. After all, we're not a library that others depend on. Bumping the lower bound would give some more `Stdlib` functionality, which some of us have already tried to use, while developing on 4.11 etc. As mentioned above, some ppx-s might still have issues with Ocaml syntax from newer versions but that would also be revealed when trying to build with a newer version.

One thing we should consider is how many CI jobs we want to have. Doing (locked + many unlocked versions) * (linux + osx) might get unnecessarily much if we try many unlocked versions. I'm not sure what the free GitHub CI limitations are, but it might cause the CI checks take longer to finish if not all of them are done in parallel or we're pushing to many branches simultaneously.

**Comment by vogler** [comment]
> Since the unlocked jobs would also check with possible updates of other packages, it might make sense to repeat that unlocked for 4.12 as well.

Yes, but that would only (in addition) check our opam constraints.

> One thing we should consider is how many CI jobs we want to have. Doing (locked + many unlocked versions) * (linux + osx) might get unnecessarily much if we try many unlocked versions. I'm not sure what the free GitHub CI limitations are, but it might cause the CI checks take longer to finish if not all of them are done in parallel or we're pushing to many branches simultaneously.

IMO it would be best if we could have some prioritized deterministic run with the lockfile which would make the CI checks green, and only afterwards the unlocked `os`/`ocaml-version` matrix.
I don't know if that's possible with GitHub actions.
Another idea for fast CI would be to only run the two `os` with lockfile for each commit and only run other versions manually or for tags/releases. There might be commits with different result between linux/macos, but between OCaml versions it's usually just some `Stdlib` function used or some dep. problem which might not be worth the churn to fix per commit but per release.

**Comment by sim642** [comment]
> MO it would be best if we could have some prioritized deterministic run with the lockfile which would make the CI checks green, and only afterwards the unlocked `os`/`ocaml-version` matrix.
> I don't know if that's possible with GitHub actions.

One option might be to schedule the full matrix to run nightly instead of on push: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule.
