### ISSUE TITLE
Rename `exp.precious_globs` and clarify what it does

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#192]
The documentation currently says

~~~OCaml
reg Experimental "exp.precious_globs"    "[]"    "Global variables that should be handled flow-sensitively when using earlyglobs."
~~~

However, Simmo discovered that "precious globs" are also "my favorite things" that exclude things from invalidation:
https://github.com/goblint/analyzer/blob/85536ab5c9cc0ffe5088af1c01eef34be27fa00e/src/analyses/base.ml#L1799-L1803

So one should rethink what `precious_globs` are, give them a sensible name, and describe their behavior.

----

Also, we should rename `exp.extraspecials` to something that better describes what it means

~~~OCaml
;reg Experimental "exp.extraspecials"     "[]"    "List of functions that must be analyzed as unknown extern functions"
~~~

**Comment by sim642** [comment]
`exp.extraspecials` just adds functions to "special" (which isn't a good name in itself) functions in `LibraryFunctions`. We should also reevaluate the default "special" functions:
https://github.com/goblint/analyzer/blob/85536ab5c9cc0ffe5088af1c01eef34be27fa00e/src/analyses/libraryFunctions.ml#L462

In #183 I already had to remove some, because apparently LDV benchmarks in SV-COMP had some custom definitions for a few of those and that was changing the behavior. Of course the whole library functions thing needs to be redone, but these default (and unremovable with any options!) "specials" can really shoot in the foot and are safer removed (and added to just the tests/programs that need them).
