### ISSUE TITLE
Register the special Apron exception printer

### ISSUE THREAD

**Issue by ivanazuzic** [goblint/analyzer#237]
As Simmo mentioned in a comment in #196:
"A good idea might be to register the special Apron exception printer with OCaml's exception printing: https://ocaml.org/learn/tutorials/error_handling.html#Printing. That way it should be possible to make unhandled Apron exceptions automatically print our all their information without having to put any try-with constructs all over these operations."

**Comment by sim642** [comment]
This was recently added into Apron itself: https://github.com/antoinemine/apron/pull/35. But there hasn't been an Apron release since then, so there are two possibilities:
1. Register the exception printer ourselves for the time being and remove it when a new Apron release comes around and we upgrade to it.
2. Pin Apron's Git repository directly instead of through opam repository. That's assuming it can be directly depended on like that (Apron isn't just an OCaml library, so there might be more layers to its build process that make this not work?)

I think option 1 would be just fine since pinning is a bit weirder with the opam template for dune.

**Comment by ivanazuzic** [comment]
> This was recently added into Apron itself: [antoinemine/apron#35](https://github.com/antoinemine/apron/pull/35). But there hasn't been an Apron release since then, so there are two possibilities:
> 
> 1. Register the exception printer ourselves for the time being and remove it when a new Apron release comes around and we upgrade to it.
> 2. Pin Apron's Git repository directly instead of through opam repository. That's assuming it can be directly depended on like that (Apron isn't just an OCaml library, so there might be more layers to its build process that make this not work?)
> 
> I think option 1 would be just fine since pinning is a bit weirder with the opam template for dune.

I vote for number 1.
