### ISSUE TITLE
Fix failing arinc semaphore regression.

### ISSUE THREAD

**Issue by vesalvojdani** [goblint/analyzer#26]
I disabled the test because it has been failing since commit 4cef73f8eb13c34dc5fde83d2f42a0d057e638f5. Remember to enable the test again once you fix the problem.

**Comment by vogler** [comment]
In https://github.com/goblint/analyzer/commit/89a6df6555d05e040af8049dd65055368e60b122 some ARINC functions like `LAP_Se_SetPartitionMode` were removed from `base` but not added somewhere else:
https://github.com/goblint/analyzer/commit/89a6df6555d05e040af8049dd65055368e60b122#diff-969b2ca0b7175f19daa5deae1308a02718e8cd1927a4d8e160541a35e57c31dbL1885-L1896

https://github.com/goblint/analyzer/blob/89a6df6555d05e040af8049dd65055368e60b122/src/analyses/libraryFunctions.ml#L406-L408

I don't get the comment. Are there other commits adding it back?

This is not the original reason why the test failed reporting races, but also makes it fail since it won't go multi-threaded?

**Comment by vogler** [comment]
The skipped test is https://github.com/goblint/analyzer/blob/master/tests/regression/17-arinc/01-sema.c.
`./scripts/update_suite.rb sema`

**Comment by michael-schwarz** [comment]
Subsumed by #792

**Comment by michael-schwarz** [comment]
Subsumed by #792

**Comment by michael-schwarz** [comment]
Subsumed by #792
