### ISSUE TITLE
inf-recursion now runs ~6x longer before stack overflow

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#265]
See https://github.com/goblint/analyzer/commit/af93e8ef032129d763b55ba5f98e988763adea1f.
```diff
- // ~15s (8MB default stack size)
+ // 1m24s (8MB default stack size) |rho|=36951 |called|=12320 |contexts|=6161
- // 1m07s (16MB, ulimit -Ss 16384)
+ // 8m48s (16MB, ulimit -Ss 16384) |rho|=73959 |called|=24656 |contexts|=12329
```
As I see it this could mean that either
1. it's now slower, so it takes longer to reach the stack overflow, or
2. it now uses less stack space.

I guess 2. is unlikely. If so, did you notice a similar regression somewhere else?
I added the numbers what the solver covered above. Could check with the commit when I added them initially.

**Comment by michael-schwarz** [comment]
So I guess this regression must be somewhere between da6b1649111a6b9c93a75783cb07d9cd16f205de and af93e8ef032129d763b55ba5f98e988763adea1f?

**Comment by michael-schwarz** [comment]
From 25f8eb4eb39438e3bee23618d8a9724d1a320069 to bce46d085af6dccdc4d20eaff42b464642038865 the runtime until StackOverflow increases from `23s` to `37s` on my machine, the difference is (#225).

However, the brunt of the change is this:

From 2a9f5c00843f6498a31e45d6501caf402d1398da to 8a74107384c466ddbbf8dffa18256365a77f9e44 the runtime until StackOverflow increases from `40s` to `02m20s` on my machine, the difference is (#227), **so it seems like the derived implementations are worse than our own?**

(The number of evaluations stays comparable 36787 before, 36808 after.)

**Comment by vogler** [comment]
It's probably worth fixing this. I just went through the changes in #227 and most of the generated implementations should be the same performance-wise as the manual ones.
It's likely just a few implementations that were replaced where there was some relevant optimization.

Some candidates:
1. I assume the generated code for tuples (`Lift2`, `Lift3`, etc.) should be the same (*lazy* left to right)?
2. changes in `basetype.ml`
2. https://github.com/goblint/analyzer/pull/227/files#diff-07d12ebad40bbdbec08af13595a6f444b4f696ec1d9304694ee6d56d5b61f389L326-L351
2. https://github.com/goblint/analyzer/pull/227/files#diff-1d69bca13b9106d6d763169d16f563b0678aaa5a24bc1c045ce441d969703287L57-L66
3. https://github.com/goblint/analyzer/pull/227/files#diff-1d69bca13b9106d6d763169d16f563b0678aaa5a24bc1c045ce441d969703287L127-L139

**Comment by sim642** [comment]
According to https://github.com/ocaml-ppx/ppx_deriving#plugins-eq-and-ord:
* "eq and ord are short-circuiting", so they should be lazy for tuples;
* "For variants, ord uses the definition order", so it should be essentially the same as the manual implementations were.

So I don't immediately know what the difference would be in these cases.

**Comment by vogler** [comment]
Concerning `| MyCFG.FunctionEntry f, MyCFG.FunctionEntry g -> compare f.vid g.vid`:
`compare f.vid g.vid` should become `CilType.Fundec.compare f g` -> `CilType.Varinfo.compare f.svar g.svar` -> `compare f.svar.vid g.svar.vid`? So `FunctionEntry`'s arg changed from `varinfo` to `fundec`?
Might be that it's those extra calls if they're not inlined.

**Comment by sim642** [comment]
I just tried it on my machine:
* https://github.com/goblint/analyzer/commit/da6b1649111a6b9c93a75783cb07d9cd16f205de (times first added) takes 27.3s
* https://github.com/goblint/analyzer/commit/af93e8ef032129d763b55ba5f98e988763adea1f (times updated to slower) takes 1min 56.9s
* https://github.com/goblint/analyzer/commit/d882d5d9bfe543c8394771257ae69734da9105b7 (current master) takes 7.2s

Not sure what to make of this. The stats for the last one are as expected:
```
runtime: 00:00:07.097
vars: 37803, evals: 37801

|rho|=37803
|called|=12604
|stable|=37803
|infl|=25199
|wpoint|=0
Found 6303 contexts for 2 functions. Top 5 functions:
6301    contexts for entry state of f on 48-inf-recursion.c:11
2       contexts for entry state of main on 48-inf-recursion.c:18

Memory statistics: total=7350.91MB, max=54.45MB, minor=7345.71MB, major=56.48MB, promoted=51.28MB
    minor collections=3508  major collections=12 compactions=0
```

**Comment by sim642** [comment]
I bisected my last difference and that improvement came from https://github.com/goblint/analyzer/commit/cd33c35f1b4856869f21ebea00df26deaf904ef7. I suppose on current master it actually will widen something with the new `side_widen` stuff? Probably not related to the original slowdown then, although this test might deserve some `PARAM` to keep the behavior consistent.

**Comment by vogler** [comment]
What's the time with `--sets exp.solver.td3.side_widen cycle`? That was the behavior before https://github.com/goblint/analyzer/commit/cd33c35f1b4856869f21ebea00df26deaf904ef7.
The new default `sides` should create fewer widening points - I'll have to think about what the reason could be why it's faster here.

**Comment by sim642** [comment]
I dug deep at the slow point https://github.com/goblint/analyzer/commit/af93e8ef032129d763b55ba5f98e988763adea1f using `perf` and found where 90% of the time is spent:
```
- camlConstraints__tf_proc_7561
    - 92,75% camlBatList__map_546
      - camlConstraints__one_function_7648
          - 91,40% camlStdlib__list__iter_258
            - camlTd3__side_3664
                - 91,24% camlStdlib__hashtbl__fold_502
                    camlStdlib__hashtbl__do_bucket_507
                  - camlBatInnerPervasives__neg_185
                      - 79,42% camlStdlib__hashtbl__mem_in_bucket_726
                        + 35,39% camlConstraints__fun_17163
                        + 33,95% camlAnalyses__fun_5385
                          1,49% caml_curry2_1
                          0,87% camlPrintable__equal_869
                      - 11,80% camlStdlib__hashtbl__mem_722
                        - 10,77% camlStdlib__hashtbl__key_index_636
                            - 7,46% camlAnalyses__hash_1050
                                3,24% camlPrintable__hash_836
                              3,23% camlConstraints__hash_8347
```

It's quite difficult to follow this because the names are mangled and certain levels have been inlined I guess, but here's what I make of it.
In `Constraints.FromSpec.tf_proc` via `one_function` via `tf_normal_call` (inlined?) it it reachces this `List.iter` and side effect, which goes into `Td3.side`:
https://github.com/goblint/analyzer/blob/af93e8ef032129d763b55ba5f98e988763adea1f/src/framework/constraints.ml#L665
Then it spends 91% of the total runtime on some `Hashtbl.fold`, which I think is from here inside `Td3.side`:
https://github.com/goblint/analyzer/blob/af93e8ef032129d763b55ba5f98e988763adea1f/src/solvers/td3.ml#L195-L196
The fold is inside `exists_key` and calls via `neg` the `Hashtbl.mem` passed as argument above:
https://github.com/goblint/analyzer/blob/af93e8ef032129d763b55ba5f98e988763adea1f/src/solvers/td3.ml#L55
There the standard implementation is the following (https://github.com/ocaml/ocaml/blob/a7f13f9acbcf2caa65aa14070cad196792a22253/stdlib/hashtbl.ml#L448-L454):
```ocaml
    let mem h key =
      let rec mem_in_bucket = function
      | Empty ->
          false
      | Cons{key=k; next} ->
          H.equal k key || mem_in_bucket next in
      mem_in_bucket h.data.(key_index h key)
```
`key_index` does the `hash` calculation, which takes 10% time in total and all the expensive stuff (80% time) must be the `equal` calls.
Due to the name mangling, I don't know what `camlConstraints__fun_17163` and `camlAnalyses__fun_5385` are (since they don't have an actual function name I'm guessing some lambdas, possibly those derived for eq. I collapsed that in `perf` output because they don't contain any insightful subcalls, just some OCaml own runtime alloc and GC functions.

So it looks like the derived `equals` for constraint system variables is somehow unusually expensive.

This point in `Td3.side` also explains why it doesn't happen on master: we now take a much less expensive side_widen choice which doesn't involve folding over the entire hashtable and `mem`-ing everything in another hashtable.

**Comment by sim642** [comment]
I tried changing the two places I just found back to use the old manually written `equal` functions and the runtime went from 1min 56.9s to 1min 10s. So there's some weird overhead for sure, but that's not the whole story. I'm guessing that same overhead might be in every derived tuple and variant `equal` then...

**Comment by sim642** [comment]
> What's the time with `--sets exp.solver.td3.side_widen cycle`? That was the behavior before [cd33c35](https://github.com/goblint/analyzer/commit/cd33c35f1b4856869f21ebea00df26deaf904ef7).

The behavior before that commit was called `cycle`, but it also changed the meaning of `cycle`. The corresponding case would be `unstable_called`, which gave me 2min 12.6s. My guess is that that increase (compared to the slowest one I gave above) is due to #251 which changes int evaluation to be via queries. And this program is basically just int evaluation, so that's not too surprising.

The new `cycle` terminates in 7.3s for me, so it's definitely that crazy `exists_key (neg (HM.mem stable)) called`. Since it's no longer the default and the new side_widen choices are more precise anyway, I think we don't have to worry about this degenerate case any more.

Of course it highlights overhead in derived implementations, but it's just such weird program with the weird side_widen that makes just `equal` calls for 70% of its runtime. Undoing #227 on master probably wouldn't give a measurable improvement with `sides`.

**Comment by vogler** [comment]
> I'm guessing that same overhead might be in every derived tuple and variant `equal` then...

Why is the generated code more expensive?
Maybe it makes sense to patch how it's generated?
Does is try physical equality first?

**Comment by sim642** [comment]
No idea, I didn't actually try looking at the code it generates. I think it's generating this
```ocaml
let equal = fun (x1, x2) (y1, y2) -> B1.equal x1 y1 && B2.equal x2 y2
```
instead of
```ocaml
let equal (x1, x2) (y1, y2) = B1.equal x1 y1 && B2.equal x2 y2
```
which seems like it should compile to the same code in the OCaml compiler, but maybe it doesn't?
Other than that, I don't know what the difference could be.

**Comment by sim642** [comment]
There could be some OCaml compilation difference because I now remember that the derived version showed some `caml_curry2_1` calls in prof, but the manually written version didn't if I remember correctly.

**Comment by vogler** [comment]
Ok, strange. Maybe add a `bench/deriving.ml` to compare tuples/variants.
Related: https://github.com/goblint/analyzer/blob/master/bench/hashcons/equality_bench.ml.
Maybe worth to always generate `... let equal a b = a == b || equal a b`?

**Comment by sim642** [comment]
@vogler I suppose we can close this issue now? Maybe you want to confirm that `--sets exp.solver.td3.side_widen unstable_called` now has the same performance as the equivalent `cycle` value used to.
