### ISSUE TITLE
Add global option to assume no overflows for signed types

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#273]
There should be some global switch that assumes no overflow for signed types for all int domains.
This would probably subsume `ana.int.wrap_on_signed_overflow` and `ana.octapron.no_signed_overflow`.

E.g., we could have `sem.int.signed_overflow` with values `'assume_none' | 'assume_top' | 'assume_wraparound'`. This would also make it clear that going to top still is an assumption and does not actually cover everything a program that has UB might do.

This would allow for better performance e.g. in SV-Comp where for tasks where reachability is checked, one may assume that there is no UB and therefore no signed overflows.

Should also not be hard to implement as we always have the `ikind` of ints in the `IntDomTuple` anyway.

**Comment by sim642** [comment]
Tbh, I'm skeptical about `ana.octapron.no_signed_overflow` in general because it only does the bound check at the outermost level (e.g. entire right-hand side of an assignment), but not any of the intermediates, which may overflow during actual execution, but don't overflow when simplified by Apron, e.g. `y = (x + x) - x`.

Having a general option under `sem` is sensible, but we'll have to see if octApron should actually be doing any of that or leaving overflow checks to just normal intervals in base.

**Comment by jerhard** [comment]
>Tbh, I'm skeptical about ana.octapron.no_signed_overflow in general because it only does the bound check at the outermost level (e.g. entire right-hand side of an assignment), but not any of the intermediates, which may overflow during actual execution, but don't overflow when simplified by Apron, e.g. y = (x + x) - x.

Could one implement an overflow check for every subexpression?

**Comment by sim642** [comment]
> Could one implement an overflow check for every subexpression?

That's not how octApron evaluates expressions though. It doesn't recurse into subexpressions but just gives the entire expression to Apron to evaluate with its best relational ability.

Also, I think there's no point in implementing subexpression overflow checks into octApron because base and the interval domain already do it and I think there's no extra precision to be gained. After #251, base queries `EvalInt` on every expression anyway, so if some subexpression has a more precise value according to octApron (which would rule out overflow), then base will know about it and the tighter interval domain bounds could avoid going into the overflow case there.

**Comment by sim642** [comment]
I suppose the bigger problem is that octApron doesn't actually know when the overflow case happens in the interval domain in base. So octApron wouldn't be invalidating some constraints it knows, which I guess is what you want from `assume_top`?

Not sure how that'd even work in the relational case because an potentially-overflowing expression like `x + y` has no value to speak of. So there's no value to change to top. Instead it's just a symbolic expressions that is used as part of assignment or restriction.

One might think of replacing that (sub)expression with some "top expression", but Apron has no such thing. And it cannot be simulated using one extra unconstrained "top" variable either, because `top - top` shouldn't be 0, but for variables Apron would find it to be. Maybe it would work if every top expression variable is generated fresh, so they're all distinct. It would be a crazy amount of complication though because variables would need to be added and removed from the Apron environment mid-evaluation.
