### ISSUE TITLE
Replace functor `IntervalFunctor` with a module

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#275]
Currently, the `IntervalFunctor` takes an `IntOps` module to allow instantiations of the interval domain to work with either `int64` or bigints. The only places that still rely on the intervals using `int64` internally are the ranges for `DefExc` and `Enums`, but these can be patched to work with bigints. 

A benefit would be that the code structure gets simpler by getting rid of the functor, and additionally, the functions in `IntDomain.Size` would work on bigints more uniformly.

**Comment by sim642** [comment]
> The only places that still rely on the intervals using `int64` internally are the ranges for `DefExc` and `Enums`, but these can be patched to work with bigints.

But these ranges represent the number of bits, not the values themselves, right? Seems way overkill to use bigints for numbers like 64 or -63.
Tbh, it'd make even more sense to switch them from `int64` to `int` (which `Size.bits` returns anyway without problem), which has even less memory overhead in the OCaml runtime.


> A benefit would be that the code structure gets simpler by getting rid of the functor

Does it actually get simpler by any extent? First, you just get rid of the functor's argument and hardcode `module Ints_t = IntOps.BigIntOps`. Second, you could inline all the `Ints_t` calls, but I'd argue it's not any easier to read `Big_int_Z.add_big_int` instead of `Ints_t.add`, etc.


> the functions in `IntDomain.Size` would work on bigints more uniformly.

I suppose you're referring to the fact that many of them still return `int64`s, but also have bigint returning versions. Surely the `int64` versions could be removed and the places that still depend on that can simply use `IntOps.of_bigint` at their own risk of erroring (which happens currently anyway as `Size` raises `Not_in_int64` in some cases).


So given the generality of the already implemented functor, I don't really see the reason to throw it away. Especially now that in #251 the flattened int domain has also been generalized to any `IntOps`.

I think there are other parts of `IntDomain` that are a much bigger source of confusion

**Comment by vogler** [comment]
> But these ranges represent the number of bits, not the values themselves, right? Seems way overkill to use bigints for numbers like 64 or -63.
> Tbh, it'd make even more sense to switch them from `int64` to `int` (which `Size.bits` returns anyway without problem), which has even less memory overhead in the OCaml runtime.

Agree

> > the functions in `IntDomain.Size` would work on bigints more uniformly.
> 
> I suppose you're referring to the fact that many of them still return `int64`s, but also have bigint returning versions. Surely the `int64` versions could be removed and the places that still depend on that can simply use `IntOps.of_bigint` at their own risk of erroring (which happens currently anyway as `Size` raises `Not_in_int64` in some cases).

I thought they only return `big_int` where needed, and use `int` or `int64` for number of bits etc.
The code was written at a time when all int domains used `int64` instead of `big_int`.
So, yes, some cleanup there would prob. be better.
