### ISSUE TITLE
Release v1.1.x on opam repository

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#282]
According to opam's CI `opam install goblint` fails for all OCaml versions they check: http://check.ocamllabs.io/?maintainers=vogler
I think it's mostly because it's hard-coded to use `4.07.1`.

A new version can be published with https://github.com/ocamllabs/dune-release.

Should we release a `goblint.1.1.0`? Idk what SemVer would be appropriate.

**Comment by michael-schwarz** [comment]
Yes, it is a good idea. I did it for CIL recently, but that turned out to be quite some work to get it into a state where it could be merged, because there was a lot of dependencies  on system packages that were not in the OPAM file.

We should also decide which of the currently close to merging PRs we would want in a Goblint release.
I would suggest that 1.5 or even 2.0 would be more appropriate since it has been several years since 1.0.

**Comment by vogler** [comment]
> because there was a lot of dependencies on system packages that were not in the OPAM file.

This is a good point. We should re-check and consolidate all this stuff:
https://github.com/goblint/analyzer/blob/cec261f79b5c25edff86223d4baa1100c63fff17/make.sh#L91-L95
Ideally we put those in opam's [depexts](https://opam.ocaml.org/doc/Manual.html#opamfield-depexts) and also install them like this for different OSes.
`git, patch, m4, autoconf, libgmp-dev, libmpfr-dev` are prob. covered by depexts of other deps. 
We can use `{with-test}` for `ruby, gem, curl`.
`javac, ant, dot (graphviz)` by default seems heavy, maybe only print this on failing `--html`?
 
> We should also decide which of the currently close to merging PRs we would want in a Goblint release.
> I would suggest that 1.5 or even 2.0 would be more appropriate since it has been several years since 1.0.

Yea, pretty arbitrary since SemVer doesn't really apply since we're no library.

**Comment by sim642** [comment]
> Yea, pretty arbitrary since SemVer doesn't really apply since we're no library.

Technically we are because of GobView. Also sensible versioning might at some point start to matter for the IDE side of interactive analysis to-be.

**Comment by vogler** [comment]
Ah, right. Of course I'm not against sensible versioning 😄

**Comment by sim642** [comment]
Now here's a problem I just found out: opam repository doesn't allow `pin-depends` for packages, but in the release branch I still have these:
https://github.com/goblint/analyzer/blob/8ed5a0b6783c104fcdf0fcce5794394abf73571e/goblint.opam#L59-L61

1. The ppx_deriving pin is simply for this performance optimization: https://github.com/ocaml-ppx/ppx_deriving/pull/252. I can temporarily remove that pin to make a release without issue.
2. The ppx_deriving_yojson pin is for a quoting problem: https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/140. Without it Goblint doesn't compile, so that's a problem. I made an issue to see if they would make a new release first: https://github.com/ocaml-ppx/ppx_deriving_yojson/issues/141. If not, then I'll have to revert to the workaround I had in Goblint previously: https://github.com/goblint/analyzer/commit/b71434644cc0b4a07d69928ff2b3b91c7933d338, which isn't a major blocker either.
3. The zarith pin from #315 is the big problem. @keremc Was there some reason the conditional patch couldn't be upstreamed to zarith? Alternatively, could the pin be moved from Goblint to Gobview?

**Comment by keremc** [comment]
@sim642 They would probably think that the patch is not worth the maintenance effort since the use case is very narrow. That being said, moving the pin to the submodule should work.

**Comment by sim642** [comment]
I already made all the pin removals as described for the 1.1.0 release. I'll do a 1.1.1 release tomorrow to fix issues with opam-ci on opam-repository.

Once all that it sorted out, I'll merget he release branch into master and also update the pins of Gobview.

**Comment by sim642** [comment]
It's now published (https://github.com/ocaml/opam-repository/pull/20132) and all the setup changes have been integrated back to master.

**Comment by michael-schwarz** [comment]
Is it intentional that on master, there are still comments for things that are TODO after  release?

https://github.com/goblint/analyzer/blob/7d4717fd2b3b5f75f093dd8e3536c21777ef7e13/goblint.opam#L60-L68

**Comment by sim642** [comment]
I intentionally kept them, yes, but I guess the "add back" is confusing. It's just to make it explicit that these pins are not necessary and can easily be removed for release and then put back again.
