### ISSUE TITLE
`Killed: 9` after `./scripts/trace_on.sh`

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#480]
~~~
$ ./goblint
Fatal error: exception Failure("No suitable function to start from.")

$ ./scripts/trace_on.sh
You can also change profile to "trace" in ./dune-workspace directly!

$ make

$ ./goblint
[1]    95033 killed     ./goblint

$ ./regtest.sh 00 01 -v
./goblint --enable dbg.debug --enable dbg.showtemps --enable dbg.regression --html  -v tests/regression/00-sanity/01-assert.c
./regtest.sh: line 20: 94944 Killed: 9

$ make clean nat

$ ./goblint
Fatal error: exception Failure("No suitable function to start from.")
~~~

**Comment by vogler** [comment]
Ok, `make clean` removes `./dune-workspace`, so tracing doesn't work at all for me.

**Comment by sim642** [comment]
Weird, I just tried and I don't get a crash like that.

I find `make clean` overly aggressive anyway because it deletes everything `.gitignore`d. `dune clean` should be sufficient for all build-related things, especially after #455.

It's especially confusing because I don't think Goblint could kill itself like that. It's not something a crash (segfault etc) would even do. Rather killing is something done by something external I think. I found this: https://apple.stackexchange.com/a/428388.

**Comment by sim642** [comment]
Looking around, there seem to be others pointing at some MacOS nonsense, e.g. running this `xcode-select --install` whatever it is: https://github.com/Homebrew/discussions/discussions/439

**Comment by vogler** [comment]
Interesting, looks like it really is this signature caching bug when replacing a binary and it's killed by macOS.
It works if I `mv` `goblint` instead of `cp`, or if I `rm -f goblint` before `cp`.

**Comment by vogler** [comment]
I replaced the `chmod +w`s with `rm -f`s.

**Comment by sim642** [comment]
Weird that it only showed when switching profiles and doing a bigger recompilation, because any code change and recompilation would change the binary, but whatever.

**Comment by vogler** [comment]
The duplication of the flags here is needed for `trace` to have the same flags as the default `dev` profile?

https://github.com/goblint/analyzer/blob/1b44c8ab285d2e9c9f814434b90b1a9f0833b364/src/dune#L92-L99

**Comment by sim642** [comment]
That was the point, yes.
