### ISSUE TITLE
Option to dump asserts in YAML-based witness format

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#741]
In a discussion between some Munich Goblint folks and @MartinSpiessl and others from the CPAChecker team on Friday we identified that as a first step of a possible co-operation (e.g. combining the strengths of Goblint as an Abstract Interpreter and Model Checkers such as CPAChecker), it would be helpful for us to produce the YAML-based invariant format (https://github.com/sosy-lab/sv-witnesses).

Since no complicated re-construction of the call-stack is needed here, I'd suggest we implement this as an additional output format for the assert instrumentation from https://github.com/goblint/analyzer/pull/157 as opposed to integrating it with all the weirdness we have for producing automaton-based witnesses.

**Comment by sim642** [comment]
This has been on my TODO list for my witness stuff for over a year, but things got really side-tracked from it...
So far there hasn't been any motivation to do this for SV-COMP either because AFAIK there's no witness validator for this format. And in SV-COMP verifiers can just emit one of the two witness formats, not both, so it would be completely devastating to do so.

One of the big problems of the entry format (compared to the automaton format) is that there's no way to apply different invariants for different contexts. So those invariants can only be join-over-all-contexts, which can make them potentially useless.
Another idea I had was to introduce a new entry type that can be conditional on some context predicate (essentially a function precondition). But before proposing that, it'd be good to first experiment on our own to see how useful it would be for SV-COMP tasks.

**Comment by michael-schwarz** [comment]
Yes, the short term goal here is not to make this the witnesses we actually output for SV-COMP. W.r.t. to not wanting to do the join over all contexts, we are also discussed extending the format to allow expressing context-sensitive information, but decided that this was not the immediate first step for now.

For the more immediate future, we had two ideas:
- Maybe re-use the information we have computed (by joining over all contexts) as a predicates to consider to CPAChecker
- Using this format as a convenient output format for invariants with the hope to "instrument" larger programs with invariants, but in a less crude way than dumping the asserts directly into the source code. We also identified how this could be helpful for incremental benchmarks, where instrumenting the program with asserts is potentially problematic, as the asserts once again change the program, leading to too much code being detected as changed.

**Comment by sim642** [comment]
> * Maybe re-use the information we have computed (by joining over all contexts) as a predicates to consider to CPAChecker

Our automaton correctness witnesses already contain invariants and CPAchecker validates those correctness witnesses, so it should already be able to consume and use those. This would just be a format for the same information.

> * Using this format as a convenient output format for invariants with the hope to "instrument" larger programs with invariants, but in a less crude way than dumping the asserts directly into the source code. We also identified how this could be helpful for incremental benchmarks, where instrumenting the program with asserts is potentially problematic, as the asserts once again change the program, leading to too much code being detected as changed.

The use of witnesses for independent program annotation (as Helmut has repeatedly described in the past) and for human-readable incremental data are also supposed to be on my agenda. I hope to finally get to all these things now.

**Comment by michael-schwarz** [comment]
> This would just be a format for the same information.

True, but it would also be an easier format and it doesn't cost us much to implement output to it (on top of our assert instrumentation). The alternative we discussed was taking our annotated program and the extracting the asserts from there via script, which imo is quite cumbersome.
