### ISSUE TITLE
Only allow one `StrPtr` in addressets 

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#807]
Some application code (such as parsers) may contain lots of string pointers. Currently, our analyses keeps all string pointers apart, potentially leading to large address sets. 
To optimize our analysis runtime, address sets should be limited to only keep at most one distinct string pointer.

**Comment by sim642** [comment]
Do you have an example of a function where this occurs? I think lex+yacc based lexers-parsers usually are switches over character literals rather than pointers to string literals. Only the latter would cause the issue, but I can't imagine a parser right now where one pointer would potentially point to so many different string literals (because these are the only strings we use a `StrPtr` for).

**Comment by michael-schwarz** [comment]
SQLite is one of the examples where this has a massive performance impact.

**Comment by sim642** [comment]
I mean a minimal reproducible example from the parser rather than the entirety of SQLite. Would be good to have some smaller benchmark than something which takes half a day to analyze.

**Comment by michael-schwarz** [comment]
The example with the parser was an anecdotal example from Helmut, not sure of we have a code example handy here.
