### ISSUE TITLE
Support for `void assume_abort_if_not(int cond) {   if(!cond) {abort();} }`

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#873]
The sv-comp people are really fond of encoding conditions that are needed to later establish correctness into calls to this function. We do not benefit from any such information at all, which we should probably fix for this year's SV-Comp.

~~~C
void assume_abort_if_not(int cond) {
  if(!cond) {abort();}
}
~~~

There are ~3000 instances of this pattern in the non-cwe part of the sv-comp `.c` files, and for some folders (e.g. `weaver`) they seem to have encoded everything into such calls :upside_down_face:

~~~C
  assume_abort_if_not(counter != 0);
  reach_error();
~~~

What I would envision would be a very cheap analysis to determine if a function is such an `assume_abort_if_not_function`:

- Takes one argument of type `int`
- Contains no assigns
- Returns only for non-zero values

If this is the case, I would meet the caller state with the condition that is passed as the argument.

**Comment by sim642** [comment]
Since the function is standardized in SV-COMP, we could just define it in `LibraryFunctions` to map into a `Assert` special function. It wouldn't be used by default because it has a definition, but then we can add it to `extraspecials` in the svcomp conf, such that it would be.

**Comment by michael-schwarz** [comment]
Is it standardized though? I can't really find a reference to it in the rules. So in principle I could have a completely different implementation in a task right?

**Comment by sim642** [comment]
It _de facto_ is. `assume_abort_if_not` was chosen to replace `__VERIFIER_assume`, just like `reach_error` was chosen to replace `__VERIFIER_error`. The new functions aren't part of the special functions listed in the rules because they have implementations, so analyzers are not strictly required to handle them specially. So there shouldn't be an alternative implementation that doesn't match the assume specification, just like there shouldn't be alternative `reach_error` implementations. If we find any, then the issue needs to be brought up in sv-benchmarks.

If we want a less SV-COMP-specific solution, we should just revive the condvars analysis, which is more general than trying to detect a particular function implementation. SV-COMP has lots of cilled benchmarks, which probably have many explicit occurrences of the pattern condvars was designed to solve. No detecting of a function shape will help us handle such conditionals in the middle of normal code, where temporaries have been introduced.

**Comment by michael-schwarz** [comment]
The other thing I started worrying about yesterday is whether us treating these functions as `extraspecial`s would need fixes for the automate based witness generation as well, so we don't just skip them and thereby restrict the witness too much?

While I agree that a more general solution would be nicer, I still think #875 is a good addition for now, and less hacky than assuming some functions having a special semantics because of their name. If we ever develop the more general solution, we can revert that again/

**Comment by michael-schwarz** [comment]
> just like there shouldn't be alternative `reach_error` implementations

Hmm, I would guess that `reach_error` only is the property of interest because it is given in the LTL property formula for most tasks (https://sv-comp.sosy-lab.org/2023/rules.php is generic in which function is given there), and it would be perfectly valid to have a `reach_error` that does return.

I think someone (Philipp?) also commented to this effect somewhere on the issues.

**Comment by sim642** [comment]
> Hmm, I would guess that `reach_error` only is the property of interest because it is given in the LTL property formula for most tasks (https://sv-comp.sosy-lab.org/2023/rules.php is generic in which function is given there

The rules have it generic, but as far as I am aware, no tool actually parses LTL. Even CPAchecker hardcodes it: https://github.com/sosy-lab/cpachecker/blob/dca35c876dafd3bfc8c08d81755ee8b9e0ec9ce3/config/specification/sv-comp-reachability.spc#L18.
