### ISSUE TITLE
Fix branching on variables

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#90]
As shown by the test case [here](https://github.com/goblint/analyzer/blob/3d54f9bab9214a20fc203d3532018d886288a8e6/tests/regression/01-cpa/35-intervals.c), branching on a variable (without an explicit comparison) currently restricts the abstract domain of the variable in question for the true branch to the abstract value [1;1] for intervals or the respective representation of 1 of the domain.
This is unsound.

**Comment by vogler** [comment]
Probably a bug with the new `invariant` function or does it also happen with the old one?

**Comment by vogler** [comment]
It's just strange that none of the existing tests caught it.
Should rethink the assert-based regression tests and replace it with something more expressive. Also, the test script should be able to check some tests with multiple configurations (e.g. all int domains separately).

**Comment by vogler** [comment]
Seems to be related to https://github.com/goblint/analyzer/commit/f1c6e572906bea3f3bd4e6b34f3574be5844c3db.
There you changed `of_bool` for `Enums` but for `Interval32` it's still zero/one. For `DefExc` it already was zero/non_zero.
Initially all of them were zero/one - should check if some place relies on one instead of non_zero and fix it.

**Comment by jerhard** [comment]
> Probably a bug with the new `invariant` function or does it also happen with the old one?

Yes, the issue does not occur when I always use the fallback

>Seems to be related to f1c6e57.

Well, in so far as the branching code caused some trouble with reaching the fixed point for enums. I initially thought I would only have to fix it there, but then it turned out that intervals were delivering spurious results, too.

> Initially all of them were zero/one - should check if some place relies on one instead of non_zero and fix it.

Yes. And there are multiple calls in Goblint that expect it to be zero/one, because they want the result of a comparsion.
But here, in the new `invariant` method, it should be zero/non zero:
https://github.com/goblint/analyzer/blob/baf07d1f10901f540ae21a69131dcb7f8d71b7ec/src/analyses/base.ml#L1495
So I guess we should add a new method `of_bool_inv_iking: ikind -> bool -> t` to the IntDomain and then use it in the `invariant`.

**Comment by vogler** [comment]
Idk, seems messy, those `{is,of,to}_{bool,int}` need some rethinking.
The problem probably arose due to the discrepancy between `of_int` and `of_bool`.
`of_int` always gives a definite value, which is why `of_bool` also did.
`{is,to}_{bool,int}` also only return true/`Some` if it is definite.
For `of_int` this works out fine since there's always a least value, but for `of_bool` there's only one for false: [1,1] and [1,2] are incomparable but both valid abstractions for true.

IMO the cleanest would be to
- get rid of `is_int` and `is_bool` in favor of `is_def/is_definite`,
- change `of_bool` to the sound non_zero for true (the places that rely on one (not many?) can use `fun x -> of_int (if x then 1L else 0L)` instead).

This breaks `assert(to_bool (of_bool true) = Some true)`, which is a bit strange name-wise, but I guess not really important.
To reduce boilerplate and potential mistakes it's probably best to just include a `Definite` module each that defines `is_def` and `to_bool` in terms of `to_int`. All these arithmetic/logical operations are also candidates for just including a functor to have some base implementation which can be overwritten on-demand.

**Comment by jerhard** [comment]
So I experimentally tried to use the zero/non-zero representation with some ad hoc implementation in the `invariant`:
https://github.com/goblint/analyzer/blob/f32918d3ce9678539599204fb792cc18da5417b5/src/analyses/base.ml#L1494-L1500
This should be sound. However, the issue is that results in a loss of precision when only the interval domain is used.
E.g. it then fails to verify the [first assert here](https://github.com/goblint/analyzer/blob/branching_fix/tests/regression/01-cpa/36-interval-branching.c).

The reason for this is that `inv_bin_int` is used to reconstruct the boolean value from the abstract value `c` with `ID.to_bool` here: 
https://github.com/goblint/analyzer/blob/f32918d3ce9678539599204fb792cc18da5417b5/src/analyses/base.ml#L1411-L1437
For intervals, this has to fail since the set `int \ {0}` cannot be represented accurately, and there is no way to reconstruct `true`.

So one option could be to just never use intervals on their own, but always in combination with `DefExc` or `Enums`.
Another option could be to enrich the `c` that is currently of type `ID.t`, e.g. with the `DefExc` domain, so one could compute with a tuple `c: (ID.t * DefExc.t)` in the invariant.

**Comment by jerhard** [comment]
> Another option could be to enrich the c that is currently of type ID.t, e.g. with the DefExc domain, so one could compute with a tuple c: (ID.t * DefExc.t) in the invariant.

I now made some [(very ugly) fix](https://github.com/goblint/analyzer/commit/f3f76e0b78f59f6066624bbe04274a8409e5f6d1) to try whether this would work. It seems like it does.

For better readable code I guess I should make an own module for dealing with `ID.t * DefExc.t` or alternatively patch `IntDomTuple` in a way to make it usable here.

**Comment by vogler** [comment]
I'll have a look at it later. Do you want to make a pull request so it's easier to see the changes and review?

**Comment by vogler** [comment]
Also make one for enums_fix against its base branch.

**Comment by vogler** [comment]
Might also want to merge in the changes from master where I pulled the common functions into a functor `IntDomain.Std`.

**Comment by vogler** [comment]
I now only use true=1 only for comparisons, and non_zero for everything else.
Maybe always adding exclusion sets would improve something for arithmetic operations, but I'm not sure if it's worth the added complexity.

Regarding `of_bool`, I changed the `DefExc` implementation to match the rest, which is in conformity with what the mli says:
https://github.com/goblint/analyzer/blob/93462fb7e4e00f040910e9cb85546705106e42a9/src/cdomains/intDomain.mli#L27-L29
Whether this is right/wrong is open for discussion. At least searching for `ID.of_bool` it looks like all those calls use it only for comparisons, which is fine.
